import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const geistSans = Vazirmatn({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "KarYaab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          rel="stylesheet"
        />
      </head>

      <body
        className={`${geistSans.variable} min-h-dvh grid grid-rows-[auto_1fr_auto] antialiased`}
        style={{ "background-color": "#f5efe7" }}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
